services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  AccessTokenBundle\Command\:
    resource: '../../Command/'
  AccessTokenBundle\Controller\:
    resource: '../../Controller/'
  AccessTokenBundle\Repository\:
    resource: '../../Repository/'
  AccessTokenBundle\Service\:
    resource: '../../Service/'
