services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\AccessTokenBundle\Command\:
    resource: '../../Command/'
  Tourze\AccessTokenBundle\Controller\:
    resource: '../../Controller/'
  Tourze\AccessTokenBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\AccessTokenBundle\Repository\:
    resource: '../../Repository/'
  Tourze\AccessTokenBundle\Service\:
    resource: '../../Service/'
